### ISSUE TITLE
自动请求URL时产生异常的问题

### ISSUE THREAD

**Issue by mzlogin** [mzlogin/csdncommenter#1]
非必现，但是今天出现过三次，两次发生在getPageCount，一次发生在comment。
属于同样的问题，某次的TraceBack:

```
Traceback (most recent call last):
  File "CsdnCommenter.py", line 153, in <module>
    csdn.autoComment()
  File "CsdnCommenter.py", line 45, in autoComment
    if self.getSourceIds() is False:
  File "CsdnCommenter.py", line 67, in getSourceIds
    pagecount = self.getPageCount()
  File "CsdnCommenter.py", line 94, in getPageCount
    html = self.sess.get(url).text
  File "D:\Programs\Python27\lib\site-packages\requests\sessions.py", line 473,
in get
    return self.request('GET', url, **kwargs)
  File "D:\Programs\Python27\lib\site-packages\requests\sessions.py", line 461,
in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Programs\Python27\lib\site-packages\requests\sessions.py", line 573,
in send
    r = adapter.send(request, **kwargs)
  File "D:\Programs\Python27\lib\site-packages\requests\adapters.py", line 415,
in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(10060, ''))
shell returned 1
Hit any key to close this window...
```

**Comment by mzlogin** [comment]
solved.
